name: Sync Shopify Products

on:
  schedule:
    - cron: '0 */2 * * *'  # cada 2 horas

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      # Aquí mapeas cada secret a una env var
      SHOPIFY_STORE:    ${{ secrets.SHOPIFY_STORE }}
      SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOP_TOKEN }}
      LOCATION_ID:      ${{ secrets.LOCATION_ID }}
      PUBLICATION_ID:   ${{ secrets.PUBLICATION_ID }}
      SUBFAMILIAS:      ${{ secrets.SUBFAMILIAS }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run sync_products.py
        run: python sync_products.py
